# 端口号
server:
  port: 3035
  servlet:
    session:
      # 设置session过期时间
      timeout: 1
# 服务应用名称
spring:
  application:
    name: SpringSecurity10security
  # The Redis settings
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
#    # Redis数据库索引(默认为0)
#    database: 0
#    # 连接超时时间（毫秒）
#    timeout: 0
#    lettuce:
#      pool:
#        # 连接池最大连接数(使用负值表示没有限制)
#        max-active: 8
#        # 连接池最大阻塞等待时间(使用负值表示没有限制)
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0

# 数据源
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#mybatis:
#  # 注意 mapper 映射文件必须使用"/"
#  type-aliases-package: com.vinjcent.pojo
#  mapper-locations: com/vinjcent/mapper/**/*.xml

# 日志处理,为了展示 mybatis 运行 sql 语句
logging:
  level:
    com:
      vinjcent:
        debug